language: bash

services:
  - docker

env:
  global:
    - REPO=zabolotny/mysql

  matrix:
    - VERSION=8.0 TAGS=8,latest
    - VERSION=5.7 TAGS=5
    - VERSION=5.6
    - VERSION=5.5

install:
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"

after_failure:
  - make logs
